# Generated by Django 4.2.1 on 2023-05-29 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_rename_mailing_id_mailingtrying_mailing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mailingmessage',
            old_name='mailing_id',
            new_name='mailing',
        ),
    ]
