# Generated by Django 4.2.1 on 2023-06-21 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0005_client_active_flg_mailing_active_flg_user_active_flg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='regularity',
            field=models.CharField(choices=[('Раз в день', 'Раз в день'), ('Раз в неделю', 'Раз в неделю'), ('Раз в месяц', 'Раз в месяц')], default='Раз в день', max_length=20, verbose_name='Периодичность'),
        ),
    ]
