# Generated by Django 4.2.1 on 2023-06-27 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0007_alter_mailingmessage_mailing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingtrying',
            name='mailing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.mailing', verbose_name='Рассылка'),
        ),
    ]
