# Generated by Django 4.2.1 on 2023-06-27 16:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0008_alter_mailingtrying_mailing'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='last_mailing_dttm',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата и время последней рассылки'),
        ),
    ]
