# Generated by Django 4.2.1 on 2023-06-28 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0009_client_last_mailing_dttm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='regularity',
            field=models.IntegerField(choices=[(1, 'Раз в день'), (7, 'Раз в неделю'), (30, 'Раз в месяц')], default=1, max_length=20, verbose_name='Периодичность'),
        ),
    ]
