# Generated by Django 4.2.1 on 2023-06-28 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0010_alter_mailing_regularity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingmessage',
            name='mailing',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='mailing.mailing'),
        ),
    ]
