# Generated by Django 4.2.1 on 2023-06-28 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0011_alter_mailingmessage_mailing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='regularity',
            field=models.IntegerField(choices=[(1, 'Раз в день'), (7, 'Раз в неделю'), (30, 'Раз в месяц')], default=1, verbose_name='Периодичность'),
        ),
        migrations.AlterField(
            model_name='mailingmessage',
            name='mailing',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='mailing.mailing'),
        ),
    ]
