# Generated by Django 4.2.1 on 2023-07-04 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0017_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'permissions': [('setting_the_mailing_status', 'Сan set mailing status')], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
    ]
